gazebo_ros_control:
  pid_gains:
    front_right_wheel: {p: 10.0, i: 0.0, d: 0.2, i_clamp: 1.0}
    front_left_wheel:  {p: 10.0, i: 0.0, d: 0.2, i_clamp: 1.0}
    rear_left_wheel:   {p: 10.0, i: 0.0, d: 0.2, i_clamp: 1.0}
    rear_right_wheel:  {p: 10.0, i: 0.0, d: 0.2, i_clamp: 1.0}
