version: "3.8"

services:
  limo-noetic-pc:
    build:
      context: ..
      dockerfile: docker_pc/pc-noetic.Dockerfile
    image: limo-noetic:pc
    container_name: limo-noetic-pc

    network_mode: host
    ipc: host

    # ◀️ 최신 compose 권장 방식
    gpus: all
    # (구버전/대안) runtime: nvidia

    environment:
      # X 포워딩
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      # ◀️ NVIDIA PRIME 오프로딩 핵심 3종
      - __NV_PRIME_RENDER_OFFLOAD=1
      - __GLX_VENDOR_LIBRARY_NAME=nvidia
      - __VK_LAYER_NV_optimus=NVIDIA_only
      # ROS
      - ROS_MASTER_URI=http://127.0.0.1:11311
      - ROS_IP=127.0.0.1
      # NVIDIA 컨테이너 런타임용 capabilities
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=graphics,utility,compute

    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ${HOME}/limo_ws:/root/ws:rw
      - /etc/localtime:/etc/localtime:ro

    # ⚠️ NVIDIA 경로에서는 /dev/dri 마운트 불필요 (있어도 되지만 권장 X)
    # devices:
    #   - /dev/dri:/dev/dri

    stdin_open: true
    tty: true
    command: ["tail","-f","/dev/null"]

